// REST Countries API endpoint
export const COUNTRIES_API = 'https://restcountries.com/v3.1/all';

// Directory for storing localization files
export const COUNTRIES_DATA_DIR = 'data/countries';

// Expected number of country localization files
export const EXPECTED_NUMBER_OF_FILES = 26;

// URL for country boundaries in GeoJSON format
export const GEOCOUNTRIES_URL =
  'https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson';

// Directory for storing polygon data files
export const POLYGON_DATA_DIR = 'data/polygon';

// Directory for storing news data files
export const NEWS_DATA_DIR = 'data/news_websites';

// Directory for storing article links
export const ARTICLES_LINKS_DIR = 'data/articles_links';

// Language-specific search keywords for news
export const SEARCH_KEYWORDS: Record<string, string> = {
  Afrikaans: 'nuus',
  Amharic: 'ዜና',
  Arabic: 'أخبار',
  Aramaic: 'Ṭebbē',
  Azerbaijani: 'xəbərlər',
  Aymara: 'yatiyäwinaka',
  Belarusian: 'навіны',
  Bengali: 'সংবাদ',
  Berber: 'Inɣmisen',
  Bislama: 'nius',
  Bosnian: 'vijesti',
  Breton: 'Keleier',
  Bulgarian: 'новини',
  'Belizean Creole': 'nyooz',
  Catalan: 'notícies',
  Czech: 'zprávy',
  Chamorro: 'notisia',
  Sorani: 'هەواڵ',
  Montenegrin: 'vijesti',
  'Seychellois Creole': 'nouvel',
  Welsh: 'newyddion',
  Danish: 'nyheder',
  German: 'nachrichten',
  Maldivian: 'ޚަބަރު',
  Dzongkha: 'གནས་ཚུལ།',
  Greek: 'ειδήσεις',
  English: 'news',
  Estonian: 'uudised',
  Basque: 'berriak',
  Faroese: 'tíðindi',
  Persian: 'اخبار',
  Fijian: 'i tukutuku',
  Filipino: 'balita',
  Finnish: 'uutiset',
  French: 'nouvelles',
  Irish: 'nuacht',
  Galician: 'novas',
  Manx: 'naight',
  Guaraní: 'marandu',
  'Haitian Creole': 'nouvèl',
  Hebrew: 'חדשות',
  Herero: 'omahungu',
  'Fiji Hindi': 'khabar',
  Hindi: 'समाचार',
  'Hiri Motu': 'rongorongo',
  Croatian: 'vijesti',
  Hungarian: 'hírek',
  Armenian: 'նորություններ',
  Icelandic: 'fréttir',
  Italian: 'notizie',
  'Jamaican Patois': 'nyuuz',
  Japanese: 'ニュース',
  Georgian: 'სიახლეები',
  Kazakh: 'жаңалықтар',
  Greenlandic: 'nutârat',
  Kalanga: 'nhau',
  Khmer: 'ព័ត៌មាន',
  Kinyarwanda: 'amakuru',
  Kyrgyz: 'жаңылыктар',
  Kikongo: 'nsangu',
  Korean: '뉴스',
  Kwangali: 'makongoero',
  Lao: 'ຂ່າວ',
  Latin: 'nuntii',
  Latvian: 'ziņas',
  Lingala: 'nsango',
  Lithuanian: 'naujienos',
  Lozi: 'makande',
  Luxembourgish: 'noriicht',
  Tshiluba: 'nsapu',
  Marshallese: 'en̄jake',
  'Hassaniya Arabic': 'Leḥbara',
  'Mauritian Creole': 'nouvel',
  Macedonian: 'вести',
  Malagasy: 'vaovao',
  Maltese: 'aħbarijiet',
  Mongolian: 'мэдээ',
  Māori: 'rongo',
  Malay: 'berita',
  Burmese: 'သတင်း',
  Khoekhoe: 'khabari',
  Nauru: 'innen',
  'Southern Ndebele': 'iindaba',
  Ndau: 'nhau',
  Ndonga: 'onghundana',
  Nepali: 'समाचार',
  Niuean: 'tala',
  Dutch: 'nieuws',
  'Norwegian Nynorsk': 'nyhende',
  'Norwegian Bokmål': 'nyheter',
  Norwegian: 'nyheter',
  Norman: 'nouvelles',
  'Northern Sotho': 'ditaba',
  Chewa: 'nkhani',
  Papiamento: 'notisia',
  Palauan: 'cheldecheduch',
  'Pitcairn-Norfolk': 'nius',
  Polish: 'wiadomości',
  Portuguese: 'notícias',
  'Upper Guinea Creole': 'notísia',
  'Dari Persian': 'اخبار',
  Pashto: 'خبرونه',
  Quechua: 'willakuykuna',
  'Cook Islands Māori': 'rongō',
  Romansh: 'novitads',
  Romanian: 'știri',
  Kirundi: 'amakuru',
  Russian: 'новости',
  Sango: 'tène',
  Sena: 'nhau',
  Sinhala: 'පුවත්',
  Slovak: 'správy',
  Slovene: 'novice',
  'Northern Sami': 'ođđasat',
  Samoan: 'tala',
  Shona: 'nhau',
  Somali: 'wararka',
  'Southern Sotho': 'litaba',
  Spanish: 'noticias',
  Albanian: 'lajme',
  Serbian: 'вести',
  Swazi: 'tindzaba',
  Swahili: 'habari',
  Swedish: 'nyheter',
  Tamil: 'செய்திகள்',
  Tetum: 'notísia',
  Tajik: 'хабарҳо',
  Tagalog: 'balita',
  Thai: 'ข่าว',
  Tigrinya: 'ዜና',
  Tokelauan: 'tala',
  'Tonga (Zambian)': 'makani',
  Tongan: 'ongoongo',
  'Tok Pisin': 'nius',
  Tswana: 'dikgang',
  Tsonga: 'mahungu',
  Turkmen: 'täzelikler',
  Turkish: 'haber',
  Tuvaluan: 'tala',
  Ukrainian: 'новини',
  Urdu: 'خبریں',
  Uzbek: 'yangiliklar',
  Venda: 'maḓivha',
  Vietnamese: 'tin tức',
  Xhosa: 'iindaba',
  Comorian: 'habari',
  Chinese: '新闻',
  Zulu: 'izindaba',
};

// Language codes for internationalization
export const LANGUAGE_CODES: Record<string, string> = {
  Afrikaans: 'af',
  Amharic: 'am',
  Arabic: 'ar',
  Aramaic: 'arc',
  Azerbaijani: 'az',
  Aymara: 'ay',
  Belarusian: 'be',
  Bengali: 'bn',
  Berber: 'ber',
  Bislama: 'bi',
  Bosnian: 'bs',
  Breton: 'br',
  Bulgarian: 'bg',
  'Belizean Creole': 'bzj',
  Catalan: 'ca',
  Czech: 'cs',
  Chamorro: 'ch',
  Sorani: 'ckb',
  Montenegrin: 'cnr',
  'Seychellois Creole': 'crs',
  Welsh: 'cy',
  Danish: 'da',
  German: 'de',
  Maldivian: 'dv',
  Dzongkha: 'dz',
  Greek: 'el',
  English: 'en',
  Estonian: 'et',
  Basque: 'eu',
  Faroese: 'fo',
  Persian: 'fa',
  Fijian: 'fj',
  Filipino: 'fil',
  Finnish: 'fi',
  French: 'fr',
  Irish: 'ga',
  Galician: 'gl',
  Manx: 'gv',
  Guaraní: 'gn',
  'Haitian Creole': 'ht',
  Hebrew: 'he',
  Herero: 'hz',
  'Fiji Hindi': 'hif',
  Hindi: 'hi',
  'Hiri Motu': 'ho',
  Croatian: 'hr',
  Hungarian: 'hu',
  Armenian: 'hy',
  Icelandic: 'is',
  Italian: 'it',
  'Jamaican Patois': 'jam',
  Japanese: 'ja',
  Georgian: 'ka',
  Kazakh: 'kk',
  Greenlandic: 'kl',
  Kalanga: 'kln',
  Khmer: 'km',
  Kinyarwanda: 'rw',
  Kyrgyz: 'ky',
  Kikongo: 'kg',
  Korean: 'ko',
  Kwangali: 'kwa',
  Lao: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  Lingala: 'ln',
  Lithuanian: 'lt',
  Lozi: 'loz',
  Luxembourgish: 'lb',
  Tshiluba: 'lua',
  Marshallese: 'mh',
  'Hassaniya Arabic': 'mey',
  'Mauritian Creole': 'mfe',
  Macedonian: 'mk',
  Malagasy: 'mg',
  Maltese: 'mt',
  Mongolian: 'mn',
  Māori: 'mi',
  Malay: 'ms',
  Burmese: 'my',
  Khoekhoe: 'kho',
  Nauru: 'na',
  'Southern Ndebele': 'nbl',
  Ndau: 'ndc',
  Ndonga: 'ng',
  Nepali: 'ne',
  Niuean: 'niu',
  Dutch: 'nl',
  'Norwegian Nynorsk': 'nn',
  'Norwegian Bokmål': 'nb',
  Norwegian: 'no',
  Norman: 'nrf',
  'Northern Sotho': 'nso',
  Chewa: 'ny',
  Papiamento: 'pap',
  Palauan: 'pau',
  'Pitcairn-Norfolk': 'pcm',
  Polish: 'pl',
  Portuguese: 'pt',
  'Upper Guinea Creole': 'pgc',
  'Dari Persian': 'prs',
  Pashto: 'ps',
  Quechua: 'qu',
  'Cook Islands Māori': 'rar',
  Romansh: 'rm',
  Romanian: 'ro',
  Kirundi: 'rn',
  Russian: 'ru',
  Sango: 'sg',
  Sena: 'seh',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovene: 'sl',
  'Northern Sami': 'sme',
  Samoan: 'sm',
  Shona: 'sn',
  Somali: 'so',
  'Southern Sotho': 'st',
  Spanish: 'es',
  Albanian: 'sq',
  Serbian: 'sr',
  Swazi: 'ss',
  Swahili: 'sw',
  Swedish: 'sv',
  Tamil: 'ta',
  Tetum: 'tet',
  Tajik: 'tg',
  Tagalog: 'tl',
  Thai: 'th',
  Tigrinya: 'ti',
  Tokelauan: 'tkl',
  'Tonga (Zambian)': 'toh',
  Tongan: 'to',
  'Tok Pisin': 'tpi',
  Tswana: 'tn',
  Tsonga: 'ts',
  Turkmen: 'tk',
  Turkish: 'tr',
  Tuvaluan: 'tvl',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Venda: 've',
  Vietnamese: 'vi',
  Xhosa: 'xh',
  Comorian: 'km',
  Chinese: 'zh',
  Zulu: 'zu',
};