// src/utils/constants.ts

// REST Countries API endpoint.
export const COUNTRIES_API = 'https://restcountries.com/v3.1/all';

// Directory for storing each localization file.
export const COUNTRIES_DATA_DIR = 'data/countries';

// URL for real country boundaries in GeoJSON format.
export const GEOCOUNTRIES_URL =
  'https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson';

// Directory for storing polygon data files.
export const POLYGON_DATA_DIR = 'data/polygon';

// Directory for storing news data files.
export const NEWS_DATA_DIR = 'data/news';

// Language-specific search keywords for news.
export const SEARCH_KEYWORDS = {
  'Afrikaans': 'nuus',
  'Amharic': 'ዜና',
  'Arabic': 'أخبار',
  'Aramaic': 'Ṭebbē',
  'Azerbaijani': 'xəbərlər',
  'Aymara': 'yatiyäwinaka',
  'Belarusian': 'навіны',
  'Bengali': 'সংবাদ',
  'Berber': 'Inɣmisen',
  'Bislama': 'nius',
  'Bosnian': 'vijesti',
  'Breton': 'Keleier',
  'Bulgarian': 'новини',
  'Belizean Creole': 'nyooz',
  'Catalan': 'notícies',
  'Czech': 'zprávy',
  'Chamorro': 'notisia',
  'Sorani': 'هەواڵ',
  'Montenegrin': 'vijesti',
  'Seychellois Creole': 'nouvel',
  'Welsh': 'newyddion',
  'Danish': 'nyheder',
  'German': 'nachrichten',
  'Maldivian': 'ޚަބަރު',
  'Dzongkha': 'གནས་ཚུལ།',
  'Greek': 'ειδήσεις',
  'English': 'news',
  'Estonian': 'uudised',
  'Basque': 'berriak',
  'Faroese': 'tíðindi',
  'Persian': 'اخبار',
  'Fijian': 'i tukutuku',
  'Filipino': 'balita',
  'Finnish': 'uutiset',
  'French': 'nouvelles',
  'Irish': 'nuacht',
  'Galician': 'novas',
  'Manx': 'naight',
  'Guaraní': 'marandu',
  'Haitian Creole': 'nouvèl',
  'Hebrew': 'חדשות',
  'Herero': 'omahungu',
  'Fiji Hindi': 'khabar',
  'Hindi': 'समाचार',
  'Hiri Motu': 'rongorongo',
  'Croatian': 'vijesti',
  'Hungarian': 'hírek',
  'Armenian': 'նորություններ',
  'Icelandic': 'fréttir',
  'Italian': 'notizie',
  'Jamaican Patois': 'nyuuz',
  'Japanese': 'ニュース',
  'Georgian': 'სიახლეები',
  'Kazakh': 'жаңалықтар',
  'Greenlandic': 'nutârat',
  'Kalanga': 'nhau',
  'Khmer': 'ព័ត៌មាន',
  'Kinyarwanda': 'amakuru',
  'Kyrgyz': 'жаңылыктар',
  'Kikongo': 'nsangu',
  'Korean': '뉴스',
  'Kwangali': 'makongoero',
  'Lao': 'ຂ່າວ',
  'Latin': 'nuntii',
  'Latvian': 'ziņas',
  'Lingala': 'nsango',
  'Lithuanian': 'naujienos',
  'Lozi': 'makande',
  'Luxembourgish': 'noriicht',
  'Tshiluba': 'nsapu',
  'Marshallese': 'en̄jake',
  'Hassaniya Arabic': 'Leḥbara',
  'Mauritian Creole': 'nouvel',
  'Macedonian': 'вести',
  'Malagasy': 'vaovao',
  'Maltese': 'aħbarijiet',
  'Mongolian': 'мэдээ',
  'Māori': 'rongo',
  'Malay': 'berita',
  'Burmese': 'သတင်း',
  'Khoekhoe': 'khabari',
  'Nauru': 'innen',
  'Southern Ndebele': 'iindaba',
  'Ndau': 'nhau',
  'Ndonga': 'onghundana',
  'Nepali': 'समाचार',
  'Niuean': 'tala',
  'Dutch': 'nieuws',
  'Norwegian Nynorsk': 'nyhende',
  'Norwegian Bokmål': 'nyheter',
  'Norwegian': 'nyheter',
  'Norman': 'nouvelles',
  'Northern Sotho': 'ditaba',
  'Chewa': 'nkhani',
  'Papiamento': 'notisia',
  'Palauan': 'cheldecheduch',
  // 'Persian (Farsi)': 'اخبار',
  'Pitcairn-Norfolk': 'nius',
  'Polish': 'wiadomości',
  'Portuguese': 'notícias',
  'Upper Guinea Creole': 'notísia',
  'Dari Persian': 'اخبار',
  'Pashto': 'خبرونه',
  'Quechua': 'willakuykuna',
  'Cook Islands Māori': 'rongō',
  'Romansh': 'novitads',
  'Romanian': 'știri',
  'Kirundi': 'amakuru',
  'Russian': 'новости',
  'Sango': 'tène',
  'Sena': 'nhau',
  'Sinhala': 'පුවත්',
  'Slovak': 'správy',
  'Slovene': 'novice',
  'Northern Sami': 'ođđasat',
  'Samoan': 'tala',
  'Shona': 'nhau',
  'Somali': 'wararka',
  'Southern Sotho': 'litaba',
  'Spanish': 'noticias',
  'Albanian': 'lajme',
  'Serbian': 'вести',
  'Swazi': 'tindzaba',
  'Swahili': 'habari',
  'Swedish': 'nyheter',
  'Tamil': 'செய்திகள்',
  'Tetum': 'notísia',
  'Tajik': 'хабарҳо',
  'Tagalog': 'balita',
  'Thai': 'ข่าว',
  'Tigrinya': 'ዜና',
  'Tokelauan': 'tala',
  'Tonga (Zambian)': 'makani',
  'Tongan': 'ongoongo',
  'Tok Pisin': 'nius',
  'Tswana': 'dikgang',
  'Tsonga': 'mahungu',
  'Turkmen': 'täzelikler',
  'Turkish': 'haber',
  'Tuvaluan': 'tala',
  'Ukrainian': 'новини',
  'Urdu': 'خبریں',
  'Uzbek': 'yangiliklar',
  'Venda': 'maḓivha',
  'Vietnamese': 'tin tức',
  'Xhosa': 'iindaba',
  'Comorian': 'habari',
  'Chinese': '新闻',
  'Zulu': 'izindaba',
};